### ISSUE TITLE
data.ub.uib.no nede

### ISSUE THREAD

**Issue by tarjelavik** [scriptotek/data.ub.uio.no#2]
Hei!
Skulle teste skosmos APi'en for å hente Humord, men siden ser ut til å være nede 😒

**Comment by danmichaelo** [comment]
Wow, noen utenfra la merke til at den var nede 😮  

Det skjer ikke *så* ofte, jeg tror det er andre gangen jeg ikke får ssh-et til maskinen og må vente på hjelp fra USIT for å få den opp igjen. Den gikk ned på lørdag og klokka 12 i dag var den opp igjen :/
