### ISSUE TITLE
Oppgradere Skosmos til 1.8?

### ISSUE THREAD

**Issue by tarjelavik** [scriptotek/data.ub.uio.no#3]
Hei, igjen!
Har dere planer om å oppgradere Skosmos? Ser dere er på 1.1 og siste release er 1.8, som har noen API-forbedringer.
Jeg og @mittinatten tester loopback.io for å lage en API for et prosjekt, der har vi laget noen wrappers for eksterne API. Da hadde det vært greit bruke siste versjon av Skosmos API :-)

**Comment by danmichaelo** [comment]
Ja, det var på tide. Oppgradert nå! Si fra hvis dere lager noe gøy :)
